-- src/test/resources/test-data/schema.sql
-- Create database schema for H2 2.x

DROP TABLE IF EXISTS agreement_risks CASCADE;
DROP TABLE IF EXISTS selected_risks CASCADE;
DROP TABLE IF EXISTS agreements CASCADE;
DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS country_risk_coefficients CASCADE;
DROP TABLE IF EXISTS age_coefficients CASCADE;
DROP TABLE IF EXISTS duration_coefficients CASCADE;
DROP TABLE IF EXISTS promo_codes CASCADE;
DROP TABLE IF EXISTS underwriting_rules CASCADE;
DROP TABLE IF EXISTS risk_types CASCADE;
DROP TABLE IF EXISTS medical_risk_limit_levels CASCADE;
DROP TABLE IF EXISTS countries CASCADE;

-- Countries table
CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_code VARCHAR(2) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Medical Risk Limit Levels table
CREATE TABLE medical_risk_limit_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_code VARCHAR(20) NOT NULL UNIQUE,
    coverage_amount DECIMAL(12,2) NOT NULL,
    base_rate DECIMAL(10,2) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Risk Types table
CREATE TABLE risk_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    base_premium DECIMAL(10,2) NOT NULL,
    is_mandatory BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Underwriting Rules table
CREATE TABLE underwriting_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    rule_type VARCHAR(50) NOT NULL,
    condition_field VARCHAR(50) NOT NULL,
    condition_operator VARCHAR(20) NOT NULL,
    condition_value VARCHAR(100) NOT NULL,
    decision VARCHAR(30) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    reason VARCHAR(255),
    priority INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Persons table
CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Agreements table
CREATE TABLE agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_number VARCHAR(50) UNIQUE,
    person_id BIGINT NOT NULL,
    country_id BIGINT NOT NULL,
    medical_level_id BIGINT NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    currency VARCHAR(3) DEFAULT 'EUR',
    total_premium DECIMAL(12,2),
    status VARCHAR(20),
    underwriting_decision VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES persons(id),
    FOREIGN KEY (country_id) REFERENCES countries(id),
    FOREIGN KEY (medical_level_id) REFERENCES medical_risk_limit_levels(id)
);

-- Agreement Risks junction table
CREATE TABLE agreement_risks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_id BIGINT NOT NULL,
    risk_type_id BIGINT NOT NULL,
    premium_amount DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agreement_id) REFERENCES agreements(id) ON DELETE CASCADE,
    FOREIGN KEY (risk_type_id) REFERENCES risk_types(id)
);

-- Selected Risks (temporary for calculation)
CREATE TABLE selected_risks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100),
    risk_code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Age Coefficients table
CREATE TABLE age_coefficients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age_from INT NOT NULL,
    age_to INT NOT NULL,
    coefficient DECIMAL(5,2) NOT NULL,
    age_group VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Country Risk Coefficients table
CREATE TABLE country_risk_coefficients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    coefficient DECIMAL(5,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (country_id) REFERENCES countries(id)
);

-- Duration Coefficients table
CREATE TABLE duration_coefficients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    days_from INT NOT NULL,
    days_to INT NOT NULL,
    coefficient DECIMAL(5,2) NOT NULL,
    description VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Promo Codes table
CREATE TABLE promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_percentage DECIMAL(5,2) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    max_uses INT,
    current_uses INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);