name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Делаем gradlew исполняемым (иначе 126)
      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          sed -i 's/\r$//' gradlew  # удаляем CRLF, оставляем LF

      # 3. Устанавливаем Java (Spring Boot 3.2.5 требует Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Сборка проекта
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
