on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 📥 Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # ☕ Java (ВАЖНО: 17, как у тебя в Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # ⚙️ Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      # 🏗️ Сборка + тесты + coverage
      - name: Build + Test + Coverage
        run: ./gradlew clean build jacocoTestReport
        env:
          SPRING_LIQUIBASE_ENABLED: false

      # 📊 SonarCloud анализ
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Normalno100_InsuranceApplication
            -Dsonar.organization=normalno100
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.1c90f204ed2dcd167a9a0efef7feaffd721488d0 }}
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=Web:S5725
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*.html